# Generated by Django 3.2.7 on 2024-04-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nitrogen', models.IntegerField(default=0)),
                ('Phosphorus', models.IntegerField(default=0)),
                ('Potassium', models.IntegerField(default=0)),
                ('Temperature', models.IntegerField(default=0)),
                ('Humidity', models.IntegerField(default=0)),
                ('pH', models.IntegerField(default=0)),
                ('Rainfall', models.IntegerField(default=0)),
                ('Crop_reco', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
