# Generated by Django 3.2.7 on 2024-04-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cropReco', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Crop_models',
        ),
    ]
